name: Report Player
version: 1.4
main: me.Coderforlife.Report.Main
softdepend: [Notifications]
website: http://dev.bukkit.org/server-mods/reprot-player

commands:
    report:
        description: Reports the player
        usage: /<command> [player]
        
        
permissons:
    report.player:
        default: true
    report.view:
        default: op