name: CoreReports
version: 1.0
main: me.crazethedev.main.Main
softdepend: [Notifications]

commands:
    report:
        description: Reports the player
        usage: /<command> [player]
        
        
permissons:
    report.player:
        default: true
    report.view:
        default: op
